### ISSUE TITLE
BugSack showing errors and Skillet is not opening

### ISSUE THREAD

**Issue by rruggles** [b-morgan/Skillet#69] opened 2022-12-13 20:43 UTC
<Please include the Skillet version number (from the title or the .toc file)>  5.00-beta3
<Please include the output of "/dump GetLocale()" if it is different than enUS> is enUS

4x bad argument #2 to '?' (Usage: self:SetParent([parent]))
[string "=[C]"]: ?
[string "=[C]"]: in function `SetParent'
[string "@Skillet/UI/MainFrame.lua"]:368: in function `ResetTradeSkillWindow'
[string "@Skillet/Skillet.lua"]:1470: in function `ShowTradeSkillWindow'
[string "@Skillet/Skillet.lua"]:1255: in function `SkilletShowWindow'
[string "@Skillet/Skillet.lua"]:923: in function `?'
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:114: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:24: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@TomTom/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceTomTom/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Thank you very much for Skillet and as another author I applaud your hard work. 
As a disabled guy I wish that I could send you money but I can't.
But I can /hug
Cheers!

**Comment by b-morgan** [comment] 2022-12-13 21:16
This is a very strange error because line 368 in MainFrame.lua is `button:SetParent("SkilletFrame")` the argument to SetParent is a constant.

Is this reproduceable? Do you remember what you were doing at the time?

**Comment by b-morgan** [comment] 2022-12-24 16:33
Closing this as no additional data is available

**Closed by b-morgan** 2022-12-24 16:33 UTC
