### ISSUE TITLE
higher tier materials not recognized?

### ISSUE THREAD

**Issue by zandadoum** [b-morgan/Skillet#71] opened 2022-12-17 11:13 UTC
<Please include the Skillet version number (from the title or the .toc file)>
skillet 5.00-beta6
<Please include the output of "/dump GetLocale()" if it is different than enUS>
enUS

being using this for years. love that this project is being continued and that there's already a version. shopping list is super useful!

ISSUE: ENGINEERING
you are probably aware of this, but here goes:
it doesn't seem to recognize higher tier of materials. example: i buy Severite Ore ** and put some bolts into the queue, but queue says i don't have any ore.

**Comment by b-morgan** [comment] 2022-12-17 12:46
This is a duplicate of #67 and the fix is complicated. In the mean time, some "band aid" fixes have been put in place so that the Blizzard UI can be opened to the recipe in question and used to create the item. Please follow the progress in that issue.

**Closed by b-morgan** 2022-12-17 12:46 UTC
