### ISSUE TITLE
Doesn't recognize higher quality reagents

### ISSUE THREAD

**Issue by Cheilynn** [b-morgan/Skillet#67] opened 2022-12-08 17:17 UTC
5.00-beta2 only recognizes rank one herbs. Rank 2 or 3 herbs in my bag are not showing as available to use for alchemy recipes.
![WoWScrnShot_120822_121129](https://user-images.githubusercontent.com/10248938/206518565-6805b111-43cc-4de4-ab8e-10ba6c0b6e13.jpg)

In this screenshot, you'll see the only herb it recognizes in this selected recipe is the saxifrage, because that is the only ingredient that I still have rank one in my bag. The other three are all rank 2 or three, so it shows as zero available.

I have not yet checked ingredients obtained from mining, as those toons are just getting started. Also have not checked if milling herbs is an issue. Will try to check these soon.

**Comment by b-morgan** [comment] 2022-12-08 18:26
This may very well be the beginning of the end for Skillet, at least for Dragon Isles recipes.

I bought some higher quality ore from the AH because my Miner / Blacksmith hasn't farmed any and I can confirm that Skillet isn't seeing the higher quality. At the moment I have no idea how to distinguish between the quality levels.

For now, you probably need to use the Blizzard UI. You can open it by using the "shift" key with whatever click you use to open Skillet. You can also put Skillet on standby with "/skillet standby on" and "/skillet standby off".

**Comment by b-morgan** [comment] 2022-12-08 19:38
Good news... I know how to distinguish between the quality levels.
Bad news... This will require a major change to Skillet's internal databases. Not to mention major new UI elements to mirror the Blizzard UI.
Bottom line... This is the end of Skillet as we know it.

**Comment by b-morgan** [comment] 2022-12-08 20:57
While this is will require a complicated solution, Skillet-5.00-beta3 will identify that a recipe has multiple quality reagents as shown below. The text "Can use multiple quality reagents" is added at the top of the detail (right) side of the frame and two new colors have been added to the required number of each reagent. Instead of red for reagents you don't have enough of, purple indicates higher quality reagents could be available and instead of white for reagents you do have enough of, yellow indicates that higher quality reagents could be used.

![MultiReagents](https://user-images.githubusercontent.com/1547854/206565026-3006e318-7e93-4d46-9cfd-319148e2e633.jpg)

**Comment by b-morgan** [comment] 2022-12-15 00:06
[Skillet-5.00-beta5](https://www.curseforge.com/wow/addons/skillet/files/4175246) is a little closer. 

There is a new option, "Use Blizzard UI for optional reagents". This will add a button to the Skillet frame which opens the Blizzard UI. When you select a recipe in the Skillet frame the Blizzard UI will select the same recipe. You can switch to the Blizzard UI and adjust your reagents that have multiple quality options and then click the Blizzard UI Create button.

Beta5 collects the data needed for these modified (multiple qualities) and finishing reagents but the Skillet UI to handle them is still a work in progress.

**Comment by b-morgan** [comment] 2022-12-16 16:52
More progress... Skillet can now display the count of each quality for modified reagents and display finishing reagents. I removed the "Can use multiple quality reagents" text but kept the colors. Let me know if this display format is acceptable or how you would make it better.
![image](https://user-images.githubusercontent.com/1547854/208147334-83325f9e-c1e6-45f4-ba9b-5ca2d896a323.png)

**Comment by b-morgan** [comment] 2022-12-24 16:41
[Skillet-5.00-beta7](https://www.curseforge.com/wow/addons/skillet/files/4259402) is the first version that will actually craft recipes with multiple quality reagents. While the UI for adjusting the quantities of these reagents exists, it isn't working yet. There are two options currently available, start at the lowest quality you have and add next highest reagent until you have enough or start at the highest quality reagent you have and add the next  lower quality until you have enough.

**Comment by b-morgan** [comment] 2022-12-26 16:25
I'm closing this issue as there has been no recent input. Reopen or create a new issue if you have any.

**Closed by b-morgan** 2022-12-26 16:25 UTC
