### ISSUE TITLE
skillet does not open

### ISSUE THREAD

**Issue by drakmakm** [b-morgan/Skillet#72] opened 2022-12-27 08:37 UTC
I'm using the latest beta release (10). The output of "/dump GetLocale()" is:[1]="frFR".

When I try to launch skillet, it plays the sound, but nothing opens.

**Comment by b-morgan** [comment] 2022-12-27 12:28
Did any of the previous 5.00 alphas or betas work for you? What other profession related addons do you have enabled?

While not logged into WoW, please rename your global saved variables file, Skillet.lua to SkilletOld.lua and delete Skillet.lua.bak and try again. If it still fails, please type "/skillet debugshow", "/skillet cleardebuglog", logoff and logon again, and then zip and upload your global saved variables files, Skillet.lua and SkilletOld.lua, and your character specific saved variables file, Skillet.lua. Please rename the character specific file if you put them all in the same zip file. Type "/skillet debugoff" to turn off debugging.

I'll look at those files and decide what further steps may be necessary.

**Comment by b-morgan** [comment] 2022-12-27 12:35
https://github.com/b-morgan/Skillet/issues/58 has some additional insight.

**Comment by drakmakm** [comment] 2022-12-27 15:11
thanks you for reply; will try that later in the evening

**Comment by drakmakm** [comment] 2022-12-28 12:36
could not yesterday evening; updating to release 5.0 and will tell you what is happening and the results you were asking.

**Comment by b-morgan** [comment] 2022-12-28 12:49
It just got approved so try again. I haven't fixed anything specific to this issue so if it is a Skillet bug, it will have to be fixed in a later release. My suspicions are that it is an addon conflict so we will have to deal with that.

**Comment by drakmakm** [comment] 2022-12-28 13:28
Here is the Zip file
[Skillet.zip](https://github.com/b-morgan/Skillet/files/10314432/Skillet.zip)

**Comment by drakmakm** [comment] 2022-12-28 13:28
thanks for your help

**Comment by b-morgan** [comment] 2022-12-28 13:48
Does it still not open?

**Comment by b-morgan** [comment] 2022-12-28 13:57
Please do another "/skillet cleardebuglog" and then "/skillet tracelog on" before opening Skillet.

I think some other addon is causing Skillet to close. Can you disable all addons except Skillet and see if Skillet will open?

**Comment by drakmakm** [comment] 2022-12-28 14:23
Still does not open unless I disable all other addons.

"/skillet cleardebuglog" and then "/skillet tracelog on" did not show anything when I clicked (all addons enabled).

**Comment by drakmakm** [comment] 2022-12-28 14:25
Found the guilty one: Ackis Recipe List. If I disable only that one, Skillet opens :).

**Comment by b-morgan** [comment] 2022-12-28 14:40
Great News! Same culprit as #58. It looks like I'll have to add a check for that addon and warn the user.

**Comment by drakmakm** [comment] 2022-12-28 14:48
thank you for your time and investigations :)

**Comment by b-morgan** [comment] 2022-12-28 14:56
So I don't need to add a warning after all... I found a bug in Skillet caused by Ackis Recipe List (which, BTW, is out-of-date and has issues of its own with 10.0.2).

Please verify that Skillet-5.01-alpha1 fixes the issue when the Ackis Recipe List is enabled.

**Comment by drakmakm** [comment] 2022-12-28 17:47
Works fine! I can open Skillet :).

Thank you very much!

**Closed** 2022-12-28 17:58 UTC
